version: '3.8'

services:

  middleware:
    build: 
      context: middleware/.
      dockerfile: Dockerfile
    env_file:
    - .env
    ports:
      - "8443:8443"

##  timescaledb:
##    image: timescale/timescaledb-ha:pg17
##    container_name: timescaledb
##    restart: unless-stopped
##    env_file:
##    - .env
##    volumes:
##      - timescaledb_data:/var/lib/postgresql/data
##    deploy:
##      resources:
##        limits:
##          cpus: "1"  
##          memory: "2GB"  
##volumes:
##  timescaledb_data:
##
