version: '3.8'

services:
  middleware:
    build: 
      context: .
      dockerfile: middleware/Dockerfile
    env_file:
    - .env
    ports:
      - "8443:8443"
        ##depends_on:
        ##   timescaledb:
        ##     condition: service_healthy
    restart: always

  timescaledb:
    image: timescale/timescaledb-ha:pg17
    container_name: timescaledb
    restart: unless-stopped
    env_file:
    - .env
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "1"  
          memory: "2GB"  
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -d mydatabase -U myuser"]
        interval: 5s
        retries: 5
        start_period: 5s
  
  local_weather:

    build:
      context: .
      dockerfile: getweather/Dockerfile
      #command: bash -c "while true; do sleep 1000; done"
      #tty: true
      #stdin_open: true
    environment:
      - PYTHONUNBUFFERED=1
    restart: always

volumes:
  timescaledb_data:

